Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:36:38
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.0.0.6:5001
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 118-985-915
127.0.0.1 - - [15/Apr/2025 16:37:13] "GET / HTTP/1.1" 200 -
Starting stock dashboard application at Tue Apr 15 16:38:33 IDT 2025
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:38:51
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.0.0.6:5001
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 118-985-915
/Users/yuval/anaconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Starting stock dashboard application at Tue Apr 15 16:50:55 IDT 2025
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:51:13
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.0.0.6:5001
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 118-985-915
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:51:31
Traceback (most recent call last):
  File "/Users/yuval/24fucking7fuckingstocksfuckme/app.py", line 244, in <module>
    app.run(debug=True, host='0.0.0.0', port=5001) 
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/werkzeug/serving.py", line 1115, in run_simple
    run_with_reloader(
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
Application stopped at Tue Apr 15 16:52:28 IDT 2025. Restarting...
Starting stock dashboard application at Tue Apr 15 16:52:30 IDT 2025
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:52:48
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.0.0.6:5001
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 118-985-915
127.0.0.1 - - [15/Apr/2025 16:53:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 16:54:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 16:54:52] "GET /api/update HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 16:54:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 17:08:43] "GET /api/update HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 17:08:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 17:09:18] "GET /api/update HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2025 17:09:18] "GET / HTTP/1.1" 200 -
 * Detected change in '/Users/yuval/24fucking7fuckingstocksfuckme/app.py', reloading
 * Detected change in '/Users/yuval/24fucking7fuckingstocksfuckme/app.py', reloading
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:53:07
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:54:52
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:58:06
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:08:43
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:09:18
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 118-985-915
 * Detected change in '/Users/yuval/24fucking7fuckingstocksfuckme/app.py', reloading
Background scheduler started at 2025-04-15 17:10:23
Next update scheduled for 2025-04-15 14:15:23.197060+00:00
Scheduler triggered update at 2025-04-15 17:10:23
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:10:40
Run time of job "update_all_stock_data (trigger: interval[0:05:00], next run at: 2025-04-15 14:12:30 UTC)" was missed by 0:03:33.260424
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 16:57:48
/Users/yuval/anaconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Application stopped at Tue Apr 15 17:11:20 IDT 2025. Restarting...
Starting stock dashboard application at Tue Apr 15 17:11:22 IDT 2025
Starting stock dashboard application at Tue Apr 15 17:11:22 IDT 2025
Background scheduler started at 2025-04-15 17:11:23
Next update scheduled for 2025-04-15 14:16:23.101782+00:00
Scheduler triggered update at 2025-04-15 17:11:23
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:11:41
 * Serving Flask app 'app'
Background scheduler started at 2025-04-15 17:11:23
Next update scheduled for 2025-04-15 14:16:23.101707+00:00
Scheduler triggered update at 2025-04-15 17:11:23
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:11:41
 * Serving Flask app 'app'
 * Debug mode: on
 * Debug mode: on
Address already in use
Port 5001 is in use by another program. Either identify and stop that program, or start the server with a different port.
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.0.0.6:5001
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Debugger is active!
 * Debugger PIN: 118-985-915
127.0.0.1 - - [15/Apr/2025 17:11:59] "GET / HTTP/1.1" 200 -
/Users/yuval/anaconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Application stopped at Tue Apr 15 17:12:03 IDT 2025. Restarting...
Starting stock dashboard application at Tue Apr 15 17:12:05 IDT 2025
Exception ignored in: <module 'threading' from '/Users/yuval/anaconda3/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/yuval/anaconda3/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/werkzeug/_reloader.py", line 452, in <lambda>
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
SystemExit: 0
Starting stock dashboard application at Tue Apr 15 17:12:05 IDT 2025
Application stopped at Tue Apr 15 17:12:05 IDT 2025. Restarting...
Application stopped at Tue Apr 15 17:12:05 IDT 2025. Restarting...
Starting stock dashboard application at Tue Apr 15 17:12:07 IDT 2025
Starting stock dashboard application at Tue Apr 15 17:12:07 IDT 2025
Background scheduler started at 2025-04-15 17:12:05
Next update scheduled for 2025-04-15 14:17:05.491008+00:00
Scheduler triggered update at 2025-04-15 17:12:05
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:12:23
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.0.0.6:5001
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
Background scheduler started at 2025-04-15 17:12:07
Next update scheduled for 2025-04-15 14:17:07.450556+00:00
Scheduler triggered update at 2025-04-15 17:12:07
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:12:24
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5001 is in use by another program. Either identify and stop that program, or start the server with a different port.
Background scheduler started at 2025-04-15 17:12:07
Next update scheduled for 2025-04-15 14:17:07.485080+00:00
Scheduler triggered update at 2025-04-15 17:12:07
Scraping data for PLTR...
Scraping data for NVDA...
Scraping data for TSLA...
Scraping data for HOOD...
Scraping data for QQQ...
Scraping data for SPY...
Scraping data for GLD...
Updated all stock data at 2025-04-15 17:12:26
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5001 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Debugger is active!
 * Debugger PIN: 118-985-915
Error submitting job "update_all_stock_data (trigger: interval[0:05:00], next run at: 2025-04-15 14:17:07 UTC)" to executor "default"
Traceback (most recent call last):
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/Users/yuval/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "update_all_stock_data (trigger: interval[0:05:00], next run at: 2025-04-15 14:17:07 UTC)" to executor "default"
Traceback (most recent call last):
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/Users/yuval/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Application stopped at Tue Apr 15 17:18:48 IDT 2025. Restarting...
Application stopped at Tue Apr 15 17:18:48 IDT 2025. Restarting...
Run time of job "update_all_stock_data (trigger: interval[0:05:00], next run at: 2025-04-15 14:17:05 UTC)" was missed by 0:01:42.576808
/Users/yuval/anaconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Error submitting job "update_all_stock_data (trigger: interval[0:05:00], next run at: 2025-04-15 14:22:05 UTC)" to executor "default"
Traceback (most recent call last):
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/Users/yuval/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
Exception ignored in: <module 'threading' from '/Users/yuval/anaconda3/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/yuval/anaconda3/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
  File "/Users/yuval/anaconda3/lib/python3.10/site-packages/werkzeug/_reloader.py", line 452, in <lambda>
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
SystemExit: 0
